<?php

use Illuminate\Database\Seeder;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    public function run()
    {
		$now = \Carbon\Carbon::now()->toDateTimeString();
		DB::table('users')->truncate();

		// Generate portable password
		$passwd = \Illuminate\Support\Facades\Hash::make('12345678');


		\DB::table('users')->insert(array (
			0 => array(
			'occupation_id' => '0',
			'first_name' => 'Teck Meng',
			'last_name' => 'Lee',
			'name' => '',
			'email' => 'tmlee@kleenso.com.my',
			'avatar' => '',
			'provider' => '',
			'provider_id' => '',
			'access_token' => '',
			'birthdate' => '0000-00-00',
			'mobile_no' => '',
			'password' => $passwd,
			'created_at'  => $now,
			'updated_at'  => $now,
			),
			1 => array (
			'occupation_id' => '0',
			'first_name' => 'try2',
			'last_name' => 'try2',
			'name' => '',
			'email' => 'try2@try2.com',
			'avatar' => '',
			'provider' => '',
			'provider_id' => '',
			'access_token' => '',
			'birthdate' => '0000-00-00',
			'mobile_no' => '',
			'password' => $passwd,
			'created_at'  => $now,
			'updated_at'  => $now,
			),
			2 => array (
			'occupation_id' => '0',
			'first_name' => 'try3',
			'last_name' => 'try3',
			'name' => '',
			'email' => 'try3@try3.com',
			'avatar' => '',
			'provider' => '',
			'provider_id' => '',
			'access_token' => '',
			'birthdate' => '0000-00-00',
			'mobile_no' => '',
			'password' => $passwd,
			'created_at'  => $now,
			'updated_at'  => $now,
			), 
		));

		$faker = Faker\Factory::create();
//		for ($i=1; $i < 50; $i++) {
//			$f= $faker->firstName($gender = null|'male'|'female');
//			$l= $faker->lastName();
//			$name= $f." ".$l;
//			DB::table('users')->insert([
//
//				'occupation_id'=>$faker->numberBetween(1,30),
//				'first_name'=>$f,
//				'last_name'=>$l,
//				'name'=> $name,
//				'nric'=>$faker->numberBetween(1000000,20000000),
//				'username'=>$faker->userName(),
//				'language_id'=>'1',
//				'nationality_country_id'=>$faker->numberBetween(1,10),
//				'gender'=>$faker->randomElement($array=array('male','female')),
//				'annual_income'=>$faker->randomElement($array=array('<30k',
//					'30-49k', '50-59k', '60-75k', '75-99k')),
//				'salutation'=>$faker->randomElement($array=array('Mr', 'Mrs', 'Ms')),
//				'email'=>'testmail'.$i.'@opensupermail.com',
//				'birthdate'=>$faker->date($format = 'Y-m-d', $max = 'now'),
//				'mobile_no'=>$faker->phoneNumber(),
//				'password'=>$passwd,
//				'created_at'=>$faker->dateTime(),
//				'default_address_id'=>'1',
//				'shipping_address_id'=>'2',
//				'deleted_at'=>$faker->dateTime(),
//				'created_at'=>$faker->dateTime(),
//				'updated_at'=>$faker->dateTime()
//				]);
//		}
//
		\DB::table('users')->insert(array (
			0 => array(
			'occupation_id' => '0',
			'first_name' => 'System',
			'last_name' => 'User',
			'name' => '',
			'email' => 'info@opensupermall.com',
			'avatar' => '',
			'provider' => '',
			'provider_id' => '',
			'access_token' => '',
			'birthdate' => '0000-00-00',
			'mobile_no' => '',
			'password' => $passwd,
			'created_at'  => $now,
			'updated_at'  => $now,
			)
		));
		// \DB::table('users')->insert(array (
		// 	0 => array(
		// 	'occupation_id' => '0',
		// 	'first_name' => 'Teck Meng',
		// 	'last_name' => 'Lee',
		// 	'name' => '',
		// 	'email' => 'tmlee@kleenso.com.my',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	1 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try2',
		// 	'last_name' => 'try2',
		// 	'name' => '',
		// 	'email' => 'try2@try2.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	2 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try3',
		// 	'last_name' => 'try3',
		// 	'name' => '',
		// 	'email' => 'try3@try3.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	3 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try4',
		// 	'last_name' => 'try34',
		// 	'name' => '',
		// 	'email' => 'try4@try4.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	4 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try5',
		// 	'last_name' => 'try5',
		// 	'name' => '',
		// 	'email' => 'try5@try5.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	5 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try6',
		// 	'last_name' => 'try6',
		// 	'name' => '',
		// 	'email' => 'try6@try6.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	6 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try7',
		// 	'last_name' => 'try7',
		// 	'name' => '',
		// 	'email' => 'try7@try7.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	7 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try8',
		// 	'last_name' => 'try8',
		// 	'name' => '',
		// 	'email' => 'try8@try8.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	8 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try9',
		// 	'last_name' => 'try9',
		// 	'name' => '',
		// 	'email' => 'try9@try9.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	9 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try10',
		// 	'last_name' => 'try10',
		// 	'name' => '',
		// 	'email' => 'try10@try10.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	10 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try11',
		// 	'last_name' => 'try11',
		// 	'name' => '',
		// 	'email' => 'try11@try11.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	11 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try12',
		// 	'last_name' => 'try12',
		// 	'name' => '',
		// 	'email' => 'try12@try12.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	12 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try13',
		// 	'last_name' => 'try13',
		// 	'name' => '',
		// 	'email' => 'try13@try13.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	13 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try14',
		// 	'last_name' => 'try14',
		// 	'name' => '',
		// 	'email' => 'try14@try14.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	14 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try15',
		// 	'last_name' => 'try15',
		// 	'name' => '',
		// 	'email' => 'try15@try15.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	15 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try16',
		// 	'last_name' => 'try16',
		// 	'name' => '',
		// 	'email' => 'try16@try16.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	16 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try17',
		// 	'last_name' => 'try17',
		// 	'name' => '',
		// 	'email' => 'try17@try17.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	17 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try18',
		// 	'last_name' => 'try18',
		// 	'name' => '',
		// 	'email' => 'try18@try18.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	18 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try19',
		// 	'last_name' => 'try19',
		// 	'name' => '',
		// 	'email' => 'try19@try19.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	19 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try19',
		// 	'last_name' => 'try19',
		// 	'name' => '',
		// 	'email' => 'try19@try19.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	19 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try20',
		// 	'last_name' => 'try20',
		// 	'name' => '',
		// 	'email' => 'try20@try20.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	20 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try21',
		// 	'last_name' => 'try21',
		// 	'name' => '',
		// 	'email' => 'try21@try21.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	21 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try22',
		// 	'last_name' => 'try22',
		// 	'name' => '',
		// 	'email' => 'try22@try22.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	22 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try23',
		// 	'last_name' => 'try23',
		// 	'name' => '',
		// 	'email' => 'try23@try23.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	23 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try24',
		// 	'last_name' => 'try24',
		// 	'name' => '',
		// 	'email' => 'try24@try24.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	24 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try25',
		// 	'last_name' => 'try25',
		// 	'name' => '',
		// 	'email' => 'try25@try25.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	25 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try26',
		// 	'last_name' => 'try26',
		// 	'name' => '',
		// 	'email' => 'try26@try26.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	26 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try27',
		// 	'last_name' => 'try27',
		// 	'name' => '',
		// 	'email' => 'try27@try27.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	27 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try28',
		// 	'last_name' => 'try28',
		// 	'name' => '',
		// 	'email' => 'try28@try28.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	28 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try29',
		// 	'last_name' => 'try29',
		// 	'name' => '',
		// 	'email' => 'try29@try29.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	29 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try30',
		// 	'last_name' => 'try30',
		// 	'name' => '',
		// 	'email' => 'try30@try30.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	30 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try31',
		// 	'last_name' => 'try31',
		// 	'name' => '',
		// 	'email' => 'try31@try31.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	31 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try32',
		// 	'last_name' => 'try32',
		// 	'name' => '',
		// 	'email' => 'try32@try32.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	32 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try33',
		// 	'last_name' => 'try33',
		// 	'name' => '',
		// 	'email' => 'try33@try33.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	33 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try34',
		// 	'last_name' => 'try34',
		// 	'name' => '',
		// 	'email' => 'try34@try34.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	34 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try35',
		// 	'last_name' => 'try35',
		// 	'name' => '',
		// 	'email' => 'try35@try35.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	35 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try36',
		// 	'last_name' => 'try36',
		// 	'name' => '',
		// 	'email' => 'try36@try36.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	36 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try37',
		// 	'last_name' => 'try37',
		// 	'name' => '',
		// 	'email' => 'try37@try37.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	37 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try38',
		// 	'last_name' => 'try38',
		// 	'name' => '',
		// 	'email' => 'try38@try38.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	38 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try39',
		// 	'last_name' => 'try39',
		// 	'name' => '',
		// 	'email' => 'try39@try39.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	39 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try40',
		// 	'last_name' => 'try40',
		// 	'name' => '',
		// 	'email' => 'try40@try40.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	40 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try41',
		// 	'last_name' => 'try41',
		// 	'name' => '',
		// 	'email' => 'try41@try41.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	41 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try42',
		// 	'last_name' => 'try42',
		// 	'name' => '',
		// 	'email' => 'try42@try42.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	42 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try43',
		// 	'last_name' => 'try43',
		// 	'name' => '',
		// 	'email' => 'try43@try43.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	43 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try44',
		// 	'last_name' => 'try44',
		// 	'name' => '',
		// 	'email' => 'try44@try44.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	44 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try45',
		// 	'last_name' => 'try45',
		// 	'name' => '',
		// 	'email' => 'try45@try45.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	45 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try46',
		// 	'last_name' => 'try46',
		// 	'name' => '',
		// 	'email' => 'try46@try46.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	46 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try47',
		// 	'last_name' => 'try47',
		// 	'name' => '',
		// 	'email' => 'try47@try47.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	47 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try48',
		// 	'last_name' => 'try48',
		// 	'name' => '',
		// 	'email' => 'try48@try48.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	48 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try49',
		// 	'last_name' => 'try49',
		// 	'name' => '',
		// 	'email' => 'try49@try49.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	49 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'try50',
		// 	'last_name' => 'try50',
		// 	'name' => '',
		// 	'email' => 'try50@try50.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	50 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'Jack',
		// 	'last_name' => '-',
		// 	'name' => '',
		// 	'email' => 'jack@eureka.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// 	51 => array (
		// 	'occupation_id' => '0',
		// 	'first_name' => 'Jordon',
		// 	'last_name' => '-',
		// 	'name' => '',
		// 	'email' => 'jordon@vtone.com',
		// 	'avatar' => '',
		// 	'provider' => '',
		// 	'provider_id' => '',
		// 	'access_token' => '',
		// 	'birthdate' => '0000-00-00',
		// 	'mobile_no' => '',
		// 	'password' => $passwd,
		// 	'created_at'  => $now,
		// 	'updated_at'  => $now,
		// 	),
		// ));
  //   }
	}
}
