<?php

use Illuminate\Database\Seeder;

class ProductTableSeeder1 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    
    public function run()
    {

       \DB::table('product')->truncate();

        
        $now = \Carbon\Carbon::now()->toDateTimeString();
        \DB::table('product')->insert(array (
            0 => array (
                'name' => 'p1',
                'brand_id' => '1',
                'category_id' => '1',
                'photo_1' => 'home1-01-cc86ceb62402ea4f084078b4e66aa8c652c50a9ae53c624220680ac6ac7b9f19.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            1 => array (
                'name' => 'p2',
                'brand_id' => '2',
                'category_id' => '1',
                'photo_1' => 'Liv-Tyler-for-Givenchy.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            2 => array (
                'name' => 'p3',
                'brand_id' => '3',
                'category_id' => '1',
                'photo_1' => 'Buy-Bag-Collection-1.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            3 => array (
                'name' => 'p4',
                'brand_id' => '4',
                'category_id' => '1',
                'photo_1' => 'image_139581893835_article.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            4 => array (
                'name' => 'p5',
                'brand_id' => '5',
                'category_id' => '1',
                'photo_1' => 'wood-furniture-design.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            5 => array (
                'name' => 'p6',
                'brand_id' => '1',
                'category_id' => '1',
                'photo_1' => 'Wedding-Event-Planner-120718122209.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            6 => array (
                'name' => 'p7',
                'brand_id' => '2',
                'category_id' => '1',
                'photo_1' => 'phone,design,electronics,watch,led,wristwatch-918c3ef7a01a42f8cb8b4b684c25dd7d_h.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            7 => array (
                'name' => 'p8',
                'brand_id' => '3',
                'category_id' => '1',
                'photo_1' => '88e151c50d6544d5_7380-w422-h336-b1-p0--contemporary-pendant-lighting.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            8 => array (
                'name' => 'p9',
                'brand_id' => '4',
                'category_id' => '2',
                'photo_1' => 'Consumer_Electronics_Accessories_Onan_Q5_Super_Slim.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            9 => array (
                'name' => 'p10',
                'brand_id' => '5',
                'category_id' => '2',
                'photo_1' => 'summer-slippers-slippers-flip-flops-shoes.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            10 => array (
                'name' => 'p11',
                'brand_id' => '1',
                'category_id' => '2',
                'photo_1' => '12_12_13_giftwrap_7.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            11 => array (
                'name' => 'p12',
                'brand_id' => '2',
                'category_id' => '2',
                'photo_1' => 'christmas-gift-wrapping.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            12 => array (
                'name' => 'p13',
                'brand_id' => '3',
                'category_id' => '2',
                'photo_1' => '88e151c50d6544d5_7380-w422-h336-b1-p0--contemporary-pendant-lighting.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            13 => array (
                'name' => 'p14',
                'brand_id' => '4',
                'category_id' => '2',
                'photo_1' => 'furniture-design-Isobel-sofa-design.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            14 => array (
                'name' => 'p15',
                'brand_id' => '5',
                'category_id' => '3',
                'photo_1' => 'images (9).jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            15 => array (
                'name' => 'p16',
                'brand_id' => '1',
                'category_id' => '6',
                'photo_1' => '416y4mkIDJL._SY300_.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            16 => array (
                'name' => 'p17',
                'brand_id' => '2',
                'category_id' => '4',
                'photo_1' => 'unique-furniture-design-idea-echoism-chair-1.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            17 => array (
                'name' => 'p18',
                'brand_id' => '3',
                'category_id' => '5',
                'photo_1' => '2015-outwear-coat-the-new-font-b-show-b-font-ladies-font-b-lambs-b-font.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            18 => array (
                'name' => 'p19',
                'brand_id' => '4',
                'category_id' => '0',
                'photo_1' => '3.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            19 => array (
                'name' => 'p20',
                'brand_id' => '5',
                'category_id' => '0',
                'photo_1' => '2.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
            20 => array (
                'name' => 'p21',
                'brand_id' => '1',
                'category_id' => '0',
                'photo_1' => '1.jpg',
                'retail_price' => '150',
                'original_price' => '200',
                'type' => 'product',
                'created_at' => $now,
                'updated_at' => $now,
            ),
        ));
		
		\DB::update("Update product SET parent_id = id WHERE segment = 'b2c'");
    }

}
