<?php

use Illuminate\Database\Seeder;

class ProductKleensoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /*
        \DB::table('product')->truncate();

        $now = \Carbon\Carbon::now()->toDateTimeString();
        \DB::table('product')->insert(array (
            0 => array (
                'name'          => 'Yalaka Foot Mask',
                'brand_id'      => 1,
                'category_id'   => 2,
                'subcat_id'     => 34,
                'subcat_level'  => 1,
                'photo_1'       => 'footmask.jpg',
				'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuan'=>30,
				'del_sarawak'=>40,
				'retail_price' => 1450,
				'original_price'=>1500,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            1 => array (
                'name'          => 'Pregnancy Test',
                'brand_id'      => 1,
                'category_id'   => 2,
                'subcat_id'     => 34,
                'subcat_level'  => 1,
                'photo_1'       => 'pregnancytest.jpg',
                'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuan'=>30,
				'del_sarawak'=>40,
				'retail_price' => 70,
				'original_price'=> 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            2 => array (
                'name'          => 'Couturing Waist & Tummy',
                'brand_id'      => 1,
                'category_id'   => 2,
                'subcat_id'     => 34,
                'subcat_level'  => 1,
                'photo_1'       => 'pregnancytest.jpg',
               'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            3 => array (
                'name'           => 'Pesso Eco Ant Bait 2pc',
                'brand_id'       => 1,
                'category_id'    => 5,
                'subcat_id'      => 83,
                'subcat_level'   => 1,
                'photo_1'        => 'pest_rep_zpsaeq4z12s.jpg',
               'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            4 => array (
                'name'           => 'Pesso Cat Repellent 500ml',
                'brand_id'       => 1,
                'category_id'    => 5,
                'subcat_id'      => 83,
                'subcat_level'   => 1,
                'photo_1'        => '500x500_F30-CON-XT.jpg',
                'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            5 => array (
                'name'           => 'Pesso Eco Cockroaches 2pc',
                'brand_id'       => 1,
                'category_id'    => 5,
                'subcat_id'      => 83,
                'subcat_level'   => 1,
                'photo_1'        => 'COCKROACHES3_zpsg967hjrk.jpg',
             'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            6 => array (
                'name'           => 'Pesso Serai Concentrated Pest Repellent 500ml',
                'brand_id'       => 1,
                'category_id'    => 5,
                'subcat_id'      => 83,
                'subcat_level'   => 1,
                'photo_1'        => 'pest_rep_zpsaeq4z12s.jpg',
                'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            7 => array (
                'name'           => 'Green Tube Termite',
                'brand_id'       => 1,
                'category_id'    => 5,
                'subcat_id'      => 83,
                'subcat_level'   => 1,
                'photo_1'        => 'green_tube_termite.jpg',
                'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            8 => array (
                'name'           => 'Pesso Cat Repellent 500ml',
                'brand_id'       => 1,
                'category_id'    => 5,
                'subcat_id'      => 83,
                'subcat_level'   => 1,
                'photo_1'        => 'pesso_cat_repellent.jpg',
                'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            9 => array (
                'name'           => 'Kleenso 9 in 1 Pink Floor Cleaner 900ml',
                'brand_id'       => 1,
                'category_id'    => 5,
                'subcat_id'      => 84,
                'subcat_level'   => 1,
                'photo_1'        => '9_in_1_pink_zpsgp00qbcm.jpg',
               'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            10 => array (
                'name'           => 'Kleenso 9 in 1 Blue Floor Cleaner 900ml',
                'brand_id'       => 1,
                'category_id'    => 5,
                'subcat_id'      => 84,
                'subcat_level'   => 1,
                'photo_1'        => '9_in_1_blue_zpsqd5bajcm.jpg',
                'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            11 => array (
                'name'           => 'Eco Glassware Stain Remover 1L',
                'brand_id'       => 1,
                'category_id'    => 5,
                'subcat_id'      => 84,
                'subcat_level'   => 1,
                'photo_1'        => 'glassware_stain_Remover_copy_zpstmtjzsuj.jpg',
               'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            12 => array (
                'name'           => 'Eco Stain Tile Remover 200',
                'brand_id'       => 1,
                'category_id'    => 5,
                'subcat_id'      => 84,
                'subcat_level'   => 1,
                'photo_1'        => 'glassware_stain_Remover_copy_zpstmtjzsuj.jpg',
                'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            13 => array (
                'name'           => 'Bacteria Pest Repellent Cleaner',
                'brand_id'       => 1,
                'category_id'    => 5,
                'subcat_id'      => 84,
                'subcat_level'   => 1,
                'photo_1'        => 'pest_rep_zpsaeq4z12s.jpg',
               'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            14 => array (
                'name'           => 'Kleenso Multi Action 500ml',
                'brand_id'       => 1,
                'category_id'    => 5,
                'subcat_id'      => 84,
                'subcat_level'   => 1,
                'photo_1'        => 'mul_action_degreser_500ml_zpslcqopd9y.png',
                'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            15 => array (
                'name'           => 'Kleenso Super Polish',
                'brand_id'       => 1,
                'category_id'    => 7,
                'subcat_id'      => 94,
                'subcat_level'   => 1,
                'photo_1'        => 'jp5.png',
               'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            16 => array (
                'name'           => 'Kleenso Leather Dashboard and Tyre Protection',
                'brand_id'       => 1,
                'category_id'    => 7,
                'subcat_id'      => 94,
                'subcat_level'   => 1,
                'photo_1'        => 'jp5.png',
              'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            17 => array (
                'name'           => 'Kleenso Tyre Shine',
                'brand_id'       => 1,
                'category_id'    => 7,
                'subcat_id'      => 94,
                'subcat_level'   => 1,
                'photo_1'        => 'jp5.png',
               'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            18 => array (
                'name'           => 'Heavy Duty Stain Remover 1L',
                'brand_id'       => 1,
                'category_id'    => 10,
                'subcat_id'      => 1,
                'subcat_level'   => 2,
                'photo_1'        => 'heavy_duty_stain_remover.jpg',
              'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            19 => array (
                'name'           => 'Heavy Duty Degreaser',
                'brand_id'       => 1,
                'category_id'    => 10,
                'subcat_id'      => 1,
                'subcat_level'   => 1,
                'photo_1'        => 'heavy_duty_degreaser.jpg',
               'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            20 => array (
                'name'           => 'Heavy Duty Grease Cut',
                'brand_id'       => 1,
                'category_id'    => 10,
                'subcat_id'      => 1,
                'subcat_level'   => 1,
                'photo_1'        => 'heavy_duty_grease_cut.jpg',
              'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            21 => array (
                'name'           => 'Odur Eleminator Sanitizer',
                'brand_id'       => 1,
                'category_id'    => 10,
                'subcat_id'      => 2,
                'subcat_level'   => 2,
                'photo_1'        => 'odur_eleminator_sanitizer.jpg',
               'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            22 => array (
                'name'           => 'Goat Milk Body Shampoo',
                'brand_id'       => 1,
                'category_id'    => 10,
                'subcat_id'      => 2,
                'subcat_level'   => 2,
                'photo_1'        => 'goat_milk_body_shampoo.jpg',
             'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            23 => array (
                'name'           => 'Laundry Detergent',
                'brand_id'       => 1,
                'category_id'    => 10,
                'subcat_id'      => 2,
                'subcat_level'   => 2,
                'photo_1'        => 'laundry_detergent.jpg',
                'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            24 => array (
                'name'           => 'Car Shampoo',
                'brand_id'       => 1,
                'category_id'    => 10,
                'subcat_id'      => 3,
                'subcat_level'   => 2,
                'photo_1'        => 'car_shampoo.jpg',
                'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            25 => array (
                'name'           => 'Car Cleaner',
                'brand_id'       => 1,
                'category_id'    => 10,
                'subcat_id'      => 3,
                'subcat_level'   => 2,
                'photo_1'        => 'car_cleaner.jpg',
              'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            ),
            26 => array (
                'name'           => 'Leather and Tyre Protectant',
                'brand_id'       => 1,
                'category_id'    => 10,
                'subcat_id'      => 3,
                'subcat_level'   => 2,
                'photo_1'        => 'leather_tyre_protectant.jpg',
                'del_worldwide'=>10,
				'del_west_malaysia'=>20,
				'del_sabah_labuah'=>30,
				'del_sarawak'=>40,
				'retail_price' => 65,
				'original_price' => 80,
				'available'=>100,
                'created_at'    => $now,
                'updated_at'    => $now,
            )
        ));
        */
    }
}
