<?php

use Illuminate\Database\Seeder;

class AddressTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    public function run()
    {
    //\DB::table('address')->truncate();
    $now = \Carbon\Carbon::now()->toDateTimeString();
    \DB::table('address')->insert(array (
		0 => array(
        'city_id' => '2467',
        'postcode' => '47600',
        'line1' => 'NO.37 & 39, JALAN INDUSTRI USJ 1/11, TAMAN PERINDUSTRIAN USJ 1,',
        'line2' => '47400 SUBANG JAYA',
        'line3' => 'SELANGOR',
        'line4' => 'MALAYSIA',
        'type' => 'billing',	
        'area_id' => 1,
        'created_at'  => $now,
        'updated_at'  => $now,
        'latitude' => 4.2105,
        'longitude' => 101.9758,
        ),
        1 => array(
        'city_id' => 'try2',
		'postcode' => 'try2',
        'line1' => 'try2',
		'line2' => 'try2',
        'line3' => 'try2',
		'line4' => 'try2',
		'type' => 'billing',
		'area_id' => 1,		
        'created_at'  => $now,
        'updated_at'  => $now,
            'latitude' => 4.2105,
        'longitude' => 101.9758,
        ),
        2 => array(
        'city_id' => 'try3',
		'postcode' => 'try3',
        'line1' => 'try3',
		'line2' => 'try3',
        'line3' => 'try3',
		'line4' => 'try3',
		'type' => 'billing',
		'area_id' => 1,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        3 => array(
        'city_id' => 'try4',
		'postcode' => 'try4',
        'line1' => 'try4',
		'line2' => 'try4',
        'line3' => 'try4',
		'line4' => 'try4',
		'type' => 'billing',
		'area_id' => 1,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        4 => array(
        'city_id' => 'try5',
		'postcode' => 'try5',
        'line1' => 'try5',
		'line2' => 'try5',
        'line3' => 'try5',
		'line4' => 'try5',
		'type' => 'billing',
		'area_id' => 1,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        5 => array(
        'city_id' => 'try6',
		'postcode' => 'try6',
        'line1' => 'try6',
		'line2' => 'try6',
        'line3' => 'try6',
		'line4' => 'try6',
		'type' => 'billing',
		'area_id' => 1,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        6 => array(
        'city_id' => 'try7',
		'postcode' => 'try7',
        'line1' => 'try7',
		'line2' => 'try7',
        'line3' => 'try7',
		'line4' => 'try7',
		'type' => 'billing',
		'area_id' => 1,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        7 => array(
        'city_id' => 'try8',
		'postcode' => 'try8',
        'line1' => 'try8',
		'line2' => 'try8',
        'line3' => 'try8',
		'line4' => 'try8',
		'type' => 'billing',
		'area_id' => 1,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        8 => array(
        'city_id' => 'try9',
		'postcode' => 'try9',
        'line1' => 'try9',
		'line2' => 'try9',
        'line3' => 'try9',
		'line4' => 'try9',
		'type' => 'billing',
		'area_id' => 1,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        9 => array(
        'city_id' => 'try10',
		'postcode' => 'try10',
        'line1' => 'try10',
		'line2' => 'try10',
        'line3' => 'try10',
		'line4' => 'try10',
		'type' => 'billing',
		'area_id' => 1,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        10 => array(
        'city_id' => 'try11',
		'postcode' => 'try11',
        'line1' => 'try11',
		'line2' => 'try11',
        'line3' => 'try11',
		'line4' => 'try11',
		'type' => 'billing',
		'area_id' => 1,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        11 => array(
        'city_id' => 'try12',
		'postcode' => 'try12',
        'line1' => 'try12',
		'line2' => 'try12',
        'line3' => 'try12',
		'line4' => 'try12',
		'type' => 'billing',
		'area_id' => 2,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        12 => array(
        'city_id' => 'try13',
		'postcode' => 'try13',
        'line1' => 'try13',
		'line2' => 'try13',
        'line3' => 'try13',
		'line4' => 'try13',
		'type' => 'billing',
		'area_id' => 2,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        13 => array(
        'city_id' => 'try14',
		'postcode' => 'try14',
        'line1' => 'try14',
		'line2' => 'try14',
        'line3' => 'try14',
		'line4' => 'try14',
		'type' => 'billing',
		'area_id' => 2,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        14 => array(
        'city_id' => 'try15',
		'postcode' => 'try15',
        'line1' => 'try15',
		'line2' => 'try15',
        'line3' => 'try15',
		'line4' => 'try15',
		'type' => 'billing',
		'area_id' => 2,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        15 => array(
        'city_id' => 'try16',
		'postcode' => 'try16',
        'line1' => 'try16',
		'line2' => 'try16',
        'line3' => 'try16',
		'line4' => 'try16',
		'type' => 'billing',
		'area_id' => 2,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        16 => array(
        'city_id' => 'try17',
		'postcode' => 'try17',
        'line1' => 'try17',
		'line2' => 'try17',
        'line3' => 'try17',
		'line4' => 'try17',
		'type' => 'billing',
		'area_id' => 2,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        17 => array(
        'city_id' => 'try18',
		'postcode' => 'try18',
        'line1' => 'try18',
		'line2' => 'try18',
        'line3' => 'try18',
		'line4' => 'try18',
		'type' => 'billing',
		'area_id' => 2,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        18 => array(
        'city_id' => 'try19',
		'postcode' => 'try19',
        'line1' => 'try19',
		'line2' => 'try19',
        'line3' => 'try19',
		'line4' => 'try19',
		'type' => 'billing',
		'area_id' => 2,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        19 => array(
        'city_id' => 'try20',
		'postcode' => 'try20',
        'line1' => 'try20',
		'line2' => 'try20',
        'line3' => 'try20',
		'line4' => 'try20',
		'type' => 'billing',
		'area_id' => 2,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        20 => array(
        'city_id' => 'try21',
		'postcode' => 'try21',
        'line1' => 'try21',
		'line2' => 'try21',
        'line3' => 'try21',
		'line4' => 'try21',
		'type' => 'billing',
		'area_id' => 3,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        21 => array(
        'city_id' => 'try22',
		'postcode' => 'try22',
        'line1' => 'try22',
		'line2' => 'try22',
        'line3' => 'try22',
		'line4' => 'try22',
		'type' => 'billing',
		'area_id' => 3,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        22 => array(
        'city_id' => 'try23',
		'postcode' => 'try23',
        'line1' => 'try23',
		'line2' => 'try23',
        'line3' => 'try23',
		'line4' => 'try23',
		'type' => 'billing',
		'area_id' => 3,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        23 => array(
        'city_id' => 'try24',
		'postcode' => 'try24',
        'line1' => 'try24',
		'line2' => 'try24',
        'line3' => 'try24',
		'line4' => 'try24',
		'type' => 'billing',
		'area_id' => 3,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        24 => array(
        'city_id' => 'try25',
		'postcode' => 'try25',
        'line1' => 'try25',
		'line2' => 'try25',
        'line3' => 'try25',
		'line4' => 'try25',
		'type' => 'billing',
		'area_id' => 3,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        25 => array(
        'city_id' => 'try26',
		'postcode' => 'try26',
        'line1' => 'try26',
		'line2' => 'try26',
        'line3' => 'try26',
		'line4' => 'try26',
		'type' => 'billing',
		'area_id' => 3,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        26 => array(
        'city_id' => 'try27',
		'postcode' => 'try27',
        'line1' => 'try27',
		'line2' => 'try27',
        'line3' => 'try27',
		'line4' => 'try27',
		'type' => 'billing',
		'area_id' => 3,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        27 => array(
        'city_id' => 'try28',
		'postcode' => 'try28',
        'line1' => 'try28',
		'line2' => 'try28',
        'line3' => 'try28',
		'line4' => 'try28',
		'type' => 'billing',
		'area_id' => 3,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        28 => array(
        'city_id' => 'try29',
		'postcode' => 'try29',
        'line1' => 'try29',
		'line2' => 'try29',
        'line3' => 'try29',
		'line4' => 'try29',
		'type' => 'billing',
		'area_id' => 3,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        29 => array(
        'city_id' => 'try30',
		'postcode' => 'try30',
        'line1' => 'try30',
		'line2' => 'try30',
        'line3' => 'try30',
		'line4' => 'try30',
		'type' => 'billing',
		'area_id' => 3,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        30 => array(
        'city_id' => 'try31',
		'postcode' => 'try31',
        'line1' => 'try31',
		'line2' => 'try31',
        'line3' => 'try31',
		'line4' => 'try31',
		'type' => 'billing',
		'area_id' => 4,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        31 => array(
        'city_id' => 'try32',
		'postcode' => 'try32',
        'line1' => 'try32',
		'line2' => 'try32',
        'line3' => 'try32',
		'line4' => 'try32',
		'type' => 'billing',
		'area_id' => 4,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        32 => array(
        'city_id' => 'try33',
		'postcode' => 'try33',
        'line1' => 'try33',
		'line2' => 'try33',
        'line3' => 'try33',
		'line4' => 'try33',
		'type' => 'billing',
		'area_id' => 4,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        33 => array(
        'city_id' => 'try34',
		'postcode' => 'try34',
        'line1' => 'try34',
		'line2' => 'try34',
        'line3' => 'try34',
		'line4' => 'try34',
		'type' => 'billing',
		'area_id' => 4,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        34 => array(
        'city_id' => 'try35',
		'postcode' => 'try35',
        'line1' => 'try35',
		'line2' => 'try35',
        'line3' => 'try35',
		'line4' => 'try35',
		'type' => 'billing',
		'area_id' => 4,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        35 => array(
        'city_id' => 'try36',
		'postcode' => 'try36',
        'line1' => 'try36',
		'line2' => 'try36',
        'line3' => 'try36',
		'line4' => 'try36',
		'type' => 'billing',
		'area_id' => 4,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        36 => array(
        'city_id' => 'try37',
		'postcode' => 'try37',
        'line1' => 'try37',
		'line2' => 'try37',
        'line3' => 'try37',
		'line4' => 'try37',
		'type' => 'billing',
		'area_id' => 4,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        37 => array(
        'city_id' => 'try38',
		'postcode' => 'try38',
        'line1' => 'try38',
		'line2' => 'try38',
        'line3' => 'try38',
		'line4' => 'try38',
		'type' => 'billing',
		'area_id' => 4,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        38 => array(
        'city_id' => 'try39',
		'postcode' => 'try39',
        'line1' => 'try39',
		'line2' => 'try39',
        'line3' => 'try39',
		'line4' => 'try39',
		'type' => 'billing',
		'area_id' => 4,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        39 => array(
        'city_id' => 'try40',
		'postcode' => 'try40',
        'line1' => 'try40',
		'line2' => 'try40',
        'line3' => 'try40',
		'line4' => 'try40',
		'type' => 'billing',
		'area_id' => 4,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        40 => array(
        'city_id' => 'try41',
		'postcode' => 'try41',
        'line1' => 'try41',
		'line2' => 'try41',
        'line3' => 'try41',
		'line4' => 'try14',
		'type' => 'billing',
		'area_id' => 5,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        41 => array(
        'city_id' => 'try42',
		'postcode' => 'try42',
        'line1' => 'try42',
		'line2' => 'try42',
        'line3' => 'try42',
		'line4' => 'try42',
		'type' => 'billing',
		'area_id' => 5,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        42 => array(
        'city_id' => 'try43',
		'postcode' => 'try43',
        'line1' => 'try43',
		'line2' => 'try43',
        'line3' => 'try43',
		'line4' => 'try43',
		'type' => 'billing',
		'area_id' => 5,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        43 => array(
        'city_id' => 'try44',
		'postcode' => 'try44',
        'line1' => 'try44',
		'line2' => 'try44',
        'line3' => 'try44',
		'line4' => 'try44',
		'type' => 'billing',
		'area_id' => 5,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        44 => array(
        'city_id' => 'try45',
		'postcode' => 'try45',
        'line1' => 'try45',
		'line2' => 'try45',
        'line3' => 'try45',
		'line4' => 'try45',
		'type' => 'billing',
		'area_id' => 5,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        45 => array(
        'city_id' => 'try46',
		'postcode' => 'try46',
        'line1' => 'try46',
		'line2' => 'try46',
        'line3' => 'try46',
		'line4' => 'try46',
		'type' => 'billing',
		'area_id' => 5,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        46 => array(
        'city_id' => 'try47',
		'postcode' => 'try47',
        'line1' => 'try47',
		'line2' => 'try47',
        'line3' => 'try47',
		'line4' => 'try47',
		'type' => 'billing',
		'area_id' => 5,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        47 => array(
        'city_id' => 'try48',
		'postcode' => 'try48',
        'line1' => 'try48',
		'line2' => 'try48',
        'line3' => 'try48',
		'line4' => 'try48',
		'type' => 'billing',
		'area_id' => 5,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        48 => array(
        'city_id' => 'try49',
		'postcode' => 'try49',
        'line1' => 'try49',
		'line2' => 'try49',
        'line3' => 'try49',
		'line4' => 'try49',
		'type' => 'billing',
		'area_id' => 5,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        49 => array(
        'city_id' => 'try50',
		'postcode' => 'try50',
        'line1' => 'try50',
		'line2' => 'try50',
        'line3' => 'try50',
		'line4' => 'try50',
		'type' => 'billing',
		'area_id' => 5,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        50 => array(
        'city_id' => 'try51',
		'postcode' => 'try51',
        'line1' => 'try51',
		'line2' => 'try51',
        'line3' => 'try51',
		'line4' => 'try51',
		'type' => 'billing',
		'area_id' => 6,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        ),
        51 => array(
        'city_id' => 'try52',
		'postcode' => 'try52',
        'line1' => 'try52',
		'line2' => 'try52',
        'line3' => 'try52',
		'line4' => 'try52',
		'type' => 'billing',
		'area_id' => 6,			
        'created_at'  => $now,
        'updated_at'  => $now,'latitude' => 4.2105,        'longitude' => 101.9758,
        )
	));
    }
    }