<?php

use Illuminate\Database\Seeder;

class BrandTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('brand')->truncate();

		$now = \Carbon\Carbon::now()->toDateTimeString();
		\DB::table('brand')->insert(array(
			0 => array (
				'name' => 'Acson',
				'description' => 'No description',
				'logo' => 'acson.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			1 => array (
				'name' => 'Adidas',
				'description' => 'No description',
				'logo' => 'adidas.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			2 => array (
				'name' => 'AGVA',
				'description' => 'No description',
				'logo' => 'agva.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			3 => array (
				'name' => 'Aire Gard',
				'description' => 'No description',
				'logo' => 'aire-gard.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			4 => array (
				'name' => 'Alba',
				'description' => 'No description',
				'logo' => 'alba.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			5 => array (
				'name' => 'Apacer',
				'description' => 'No description',
				'logo' => 'apacer.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			6 => array (
				'name' => 'Asus',
				'description' => 'No description',
				'logo' => 'asus.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			7 => array (
				'name' => 'AVF',
				'description' => 'No description',
				'logo' => 'avf.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			8 => array (
				'name' => 'Bata',
				'description' => 'No description',
				'logo' => 'bata.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			9 => array (
				'name' => "Brom's",
				'description' => 'No description',
				'logo' => "brom's.jpg",
				'created_at' => $now,
				'updated_at' => $now,
			),
			10 => array (
				'name' => 'Caely',
				'description' => 'No description',
				'logo' => 'caely.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			11 => array (
				'name' => 'Casio',
				'description' => 'No description',
				'logo' => 'casio.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			12 => array (
				'name' => 'Celcom',
				'description' => 'No description',
				'logo' => 'celcom.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			13 => array (
				'name' => 'Cybex',
				'description' => 'No description',
				'logo' => 'cybex.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			14 => array (
				'name' => 'Daikin',
				'description' => 'No description',
				'logo' => 'daikin.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			15 => array (
				'name' => 'Digi',
				'description' => 'No description',
				'logo' => 'digi.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			16 => array (
				'name' => 'Dyson',
				'description' => 'No description',
				'logo' => 'dyson.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			17 => array (
				'name' => 'Esprit',
				'description' => 'No description',
				'logo' => 'esprit.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			18 => array (
				'name' => 'Flexi Supreme',
				'description' => 'No description',
				'logo' => 'flexi-supreme.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			19 => array (
				'name' => 'Four Seas',
				'description' => 'No description',
				'logo' => 'four_seas.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			20 => array (
				'name' => 'Gintell',
				'description' => 'No description',
				'logo' => 'gintell.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			21 => array (
				'name' => 'Gong Zai',
				'description' => 'No description',
				'logo' => 'gong_zai.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			22 => array (
				'name' => 'Haba',
				'description' => 'No description',
				'logo' => 'haba.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			23 => array (
				'name' => "Han's Laser",
				'description' => 'No description',
				'logo' => "han's laser.jpg",
				'created_at' => $now,
				'updated_at' => $now,
			),
			24 => array (
				'name' => 'Happy',
				'description' => 'No description',
				'logo' => 'happy.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			25 => array (
				'name' => 'Hauck',
				'description' => 'No description',
				'logo' => 'hauck.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			26 => array (
				'name' => 'HotLink',
				'description' => 'No description',
				'logo' => 'hotlink.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			27 => array (
				'name' => 'Houm',
				'description' => 'No description',
				'logo' => 'houm.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			28 => array (
				'name' => 'HP',
				'description' => 'No description',
				'logo' => 'hp.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			29 => array (
				'name' => 'I Talk',
				'description' => 'No description',
				'logo' => 'i-talk.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			30 => array (
				'name' => 'Ideal Home',
				'description' => 'No description',
				'logo' => 'ideal-home.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			31 => array (
				'name' => 'Inadays',
				'description' => 'No description',
				'logo' => 'inadays.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			32 => array (
				'name' => 'Jabra',
				'description' => 'No description',
				'logo' => 'jabra.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			33 => array (
				'name' => 'Jotono',
				'description' => 'No description',
				'logo' => 'jotono.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			34 => array (
				'name' => 'Kasumi Beauty',
				'description' => 'No description',
				'logo' => 'kasumi-beauty.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			35 => array (
				'name' => 'Kleengard',
				'description' => 'No description',
				'logo' => 'kleengard.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			36 => array (
				'name' => 'KMS',
				'description' => 'No description',
				'logo' => 'kms.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			37 => array (
				'name' => 'Logitech',
				'description' => 'No description',
				'logo' => 'logitech.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			38 => array (
				'name' => 'Madame Nyonya',
				'description' => 'No description',
				'logo' => 'madame-nyonya.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			39 => array (
				'name' => 'Maxis',
				'description' => 'No description',
				'logo' => 'maxis.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			40 => array (
				'name' => 'Meiko',
				'description' => 'No description',
				'logo' => 'meiko.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			41 => array (
				'name' => 'Midea',
				'description' => 'No description',
				'logo' => 'midea.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			42 => array (
				'name' => 'Minotti',
				'description' => 'No description',
				'logo' => 'minotti.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			43 => array (
				'name' => 'MST',
				'description' => 'No description',
				'logo' => 'mst.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			44 => array (
				'name' => 'Nagamas',
				'description' => 'No description',
				'logo' => 'nagamas.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			45 => array (
				'name' => 'Nuby',
				'description' => 'No description',
				'logo' => 'nuby.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			46 => array (
				'name' => 'Osafe Fire Inspection',
				'description' => 'No description',
				'logo' => 'osafe.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			47 => array (
				'name' => 'Pest Aid',
				'description' => 'No description',
				'logo' => 'pest-aid.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			48 => array (
				'name' => 'Philips Avent',
				'description' => 'No description',
				'logo' => 'philips-avent.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			49 => array (
				'name' => 'Plus',
				'description' => 'No description',
				'logo' => 'plus.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			50 => array (
				'name' => 'Puma',
				'description' => 'No description',
				'logo' => 'puma.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			51 => array (
				'name' => 'Pepsi',
				'description' => 'No description',
				'logo' => 'pepsi',
				'created_at' => $now,
				'updated_at' => $now,
			),
			52 => array (
				'name' => 'Renault',
				'description' => 'No description',
				'logo' => 'renault.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			53 => array (
				'name' => 'Silky',
				'description' => 'No description',
				'logo' => 'silky.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			54 => array (
				'name' => 'VBG',
				'description' => 'No description',
				'logo' => 'vbg.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			55 => array (
				'name' => 'Thermos',
				'description' => 'No description',
				'logo' => 'thermos.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			56 => array (
				'name' => 'Thule',
				'description' => 'No description',
				'logo' => 'thule.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			57 => array (
				'name' => 'Tirana',
				'description' => 'No description',
				'logo' => 'tirana.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			58 => array (
				'name' => 'Tune Talk',
				'description' => 'No description',
				'logo' => 'tune-talk.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			59 => array (
				'name' => 'U Mobile',
				'description' => 'No description',
				'logo' => 'u-mobile.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			60 => array (
				'name' => 'Uberman',
				'description' => 'No description',
				'logo' => 'uberman.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			61 => array (
				'name' => 'Usana',
				'description' => 'No description',
				'logo' => 'usana.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			62 => array (
				'name' => 'XOX',
				'description' => 'No description',
				'logo' => 'xox.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
			63 => array (
				'name' => 'Xpax',
				'description' => 'No description',
				'logo' => 'xpax.jpg',
				'created_at' => $now,
				'updated_at' => $now,
			),
 			64 => array (
 				'name' => 'Yan Da',
 				'description' => 'No description',
 				'logo' => 'yan-da.jpg',
 				'created_at' => $now,
 				'updated_at' => $now,
 			),
 			65 => array (
 				'name' => 'YorShin',
 				'description' => 'No description',
 				'logo' => 'yorshin.jpg',
 				'created_at' => $now,
 				'updated_at' => $now,
 			),
		));
	}
}
