<?php

use Illuminate\Database\Seeder;

class OcbcRejectTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    public function run()
    {
        \DB::table('ocbcgiro_reject')->truncate();
        $now = \Carbon\Carbon::now()->toDateTimeString();
        \DB::table('ocbcgiro_reject')->insert(array (

			1 => array (
				'code' => '001',
				'description' => 'No Account / Unable to Locate Account',
				'remarks' => 'A/C not on file',
				'created_at' => $now,
				'updated_at' => $now,
			),
			2 => array (
				'code' => '005',
				'description' => 'Insufficient Fund',
				'remarks' => 'Insufficient fund',
				'created_at' => $now,
				'updated_at' => $now,
			),
			3 => array (
				'code' => '007',
				'description' => 'Rejected due to Account Status',
				'remarks' => 'AC/TD is closed or Closed Account',
				'created_at' => $now,
				'updated_at' => $now,
			),
			4 => array (
				'code' => '008',
				'description' => 'Rejected due to Account Status',
				'remarks' => 'Dormant Account',
				'created_at' => $now,
				'updated_at' => $now,
			),
			5 => array (
				'code' => '009',
				'description' => 'Rejected due to Account Status',
				'remarks' => 'Restricted Account',
				'created_at' => $now,
				'updated_at' => $now,
			),
			6 => array (
				'code' => '010',
				'description' => 'Rejected due to Account Status',
				'remarks' => 'Frozen Account',
				'created_at' => $now,
				'updated_at' => $now,
			),
			7 => array (
				'code' => '014',
				'description' => 'Bal less than minimum',
				'remarks' => 'Bal less than minimum',
				'created_at' => $now,
				'updated_at' => $now,
			),
			8 => array (
				'code' => '015',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'Trans. > payoff',
				'created_at' => $now,
				'updated_at' => $now,
			),
			9 => array (
				'code' => '016',
				'description' => 'Trans. > ledger balance',
				'remarks' => 'Trans. > ledger balance',
				'created_at' => $now,
				'updated_at' => $now,
			),
			10 => array (
				'code' => '017',
				'description' => 'Rejected due to Account Status',
				'remarks' => "Frozen/0 Ac'l A/C",
				'created_at' => $now,
				'updated_at' => $now,
			),
			11 => array (
				'code' => '033',
				'description' => 'Rejected due to Account Status',
				'remarks' => 'Deceased customer',
				'created_at' => $now,
				'updated_at' => $now,
			),
			12 => array (
				'code' => '048',
				'description' => 'Rejected due to Account Status',
				'remarks' => 'AC/TD close today',
				'created_at' => $now,
				'updated_at' => $now,
			),
			13 => array (
				'code' => '060',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'Account pending dual ctrl',
				'created_at' => $now,
				'updated_at' => $now,
			),
			14 => array (
				'code' => '065',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'No loan released yet',
				'created_at' => $now,
				'updated_at' => $now,
			),
			15 => array (
				'code' => '075',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'Charged off loan',
				'created_at' => $now,
				'updated_at' => $now,
			),
			16 => array (
				'code' => '076',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'Sold participation',
				'created_at' => $now,
				'updated_at' => $now,
			),
			17 => array (
				'code' => '083',
				'description' => 'Transaction Cannot be Completed or Rejected due to Account Status',
				'remarks' => '03 Staff A/C or 03 Bad Account',
				'created_at' => $now,
				'updated_at' => $now,
			),
			18 => array (
				'code' => '085',
				'description' => 'Rejected due to Account Status',
				'remarks' => '05 External A/C',
				'created_at' => $now,
				'updated_at' => $now,
			),
			19 => array (
				'code' => '086',
				'description' => 'Rejected due to Account Status',
				'remarks' => '06 Frozen',
				'created_at' => $now,
				'updated_at' => $now,
			),
			20 => array (
				'code' => '087',
				'description' => 'Rejected due to Account Status',
				'remarks' => '07 Deceased A/C',
				'created_at' => $now,
				'updated_at' => $now,
			),
			21 => array (
				'code' => '093',
				'description' => 'Rejected due to Account Status',
				'remarks' => '13 Under Litigation',
				'created_at' => $now,
				'updated_at' => $now,
			),
			22 => array (
				'code' => '095',
				'description' => 'Housing Development Acct',
				'remarks' => '15 Housing Development Acct',
				'created_at' => $now,
				'updated_at' => $now,
			),
			23 => array (
				'code' => '097',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => '17 Court Hold',
				'created_at' => $now,
				'updated_at' => $now,
			),
			24 => array (
				'code' => '104',
				'description' => 'Refer Debit',
				'remarks' => '24 Refer Debits',
				'created_at' => $now,
				'updated_at' => $now,
			),
			25 => array (
				'code' => '107',
				'description' => 'Post No Debits',
				'remarks' => '27 Post No Debits',
				'created_at' => $now,
				'updated_at' => $now,
			),
			26 => array (
				'code' => '109',
				'description' => 'Rejected due to Account Status',
				'remarks' => '29 Dormant',
				'created_at' => $now,
				'updated_at' => $now,
			),
			27 => array (
				'code' => '110',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => '30 Unclaimed',
				'created_at' => $now,
				'updated_at' => $now,
			),
			28 => array (
				'code' => '112',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => '32 Refer Credits',
				'created_at' => $now,
				'updated_at' => $now,
			),
			29 => array (
				'code' => '113',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => '33 Foreign Currency Account',
				'created_at' => $now,
				'updated_at' => $now,
			),
			30 => array (
				'code' => '123',
				'description' => 'Rejected due to Account Status',
				'remarks' => 'AC/TD is closed',
				'created_at' => $now,
				'updated_at' => $now,
			),
			31 => array (
				'code' => '127',
				'description' => 'Rejected due to Account Status or Transaction Cannot be Completed',
				'remarks' => 'Account status is invalid or Written off a/c',
				'created_at' => $now,
				'updated_at' => $now,
			),
			32 => array (
				'code' => '135',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'Non-performing status',
				'created_at' => $now,
				'updated_at' => $now,
			),
			33 => array (
				'code' => '138',
				'description' => 'Overdrawn not allowed',
				'remarks' => 'Overdrawn not allowed',
				'created_at' => $now,
				'updated_at' => $now,
			),
			34 => array (
				'code' => '151',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'Trx not allowed',
				'created_at' => $now,
				'updated_at' => $now,
			),
			35 => array (
				'code' => '169',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'Exceed Max No. of Deposit',
				'created_at' => $now,
				'updated_at' => $now,
			),
			36 => array (
				'code' => '170',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'Exceed Max Amt of Deposit',
				'created_at' => $now,
				'updated_at' => $now,
			),
			37 => array (
				'code' => '192',
				'description' => 'Duplicate error',
				'remarks' => 'Duplicate error',
				'created_at' => $now,
				'updated_at' => $now,
			),
			38 => array (
				'code' => '216',
				'description' => 'Negative available bal',
				'remarks' => 'Negative available bal',
				'created_at' => $now,
				'updated_at' => $now,
			),
			39 => array (
				'code' => '217',
				'description' => 'Negative available bal',
				'remarks' => 'Negative available bal',
				'created_at' => $now,
				'updated_at' => $now,
			),
			40 => array (
				'code' => '239',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'Loan is paid off',
				'created_at' => $now,
				'updated_at' => $now,
			),
			41 => array (
				'code' => '240',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'Eff Date< Origination Date',
				'created_at' => $now,
				'updated_at' => $now,
			),
			42 => array (
				'code' => '254',
				'description' => 'Insuff Bal/OD Limit Exceed',
				'remarks' => 'Insuff Bal/OD Limit Exceed',
				'created_at' => $now,
				'updated_at' => $now,
			),
			43 => array (
				'code' => '260',
				'description' => 'Over transaction limit',
				'remarks' => 'Over transaction limit',
				'created_at' => $now,
				'updated_at' => $now,
			),
			44 => array (
				'code' => '419',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'NPL Status="9"-Loss',
				'created_at' => $now,
				'updated_at' => $now,
			),
			45 => array (
				'code' => '421',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'NPL Status="7"-Doubtful',
				'created_at' => $now,
				'updated_at' => $now,
			),
			46 => array (
				'code' => '426',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'NPL Status="2"-Sub Std',
				'created_at' => $now,
				'updated_at' => $now,
			),
			47 => array (
				'code' => '452',
				'description' => 'Trans Not Allow Fr This Prd',
				'remarks' => 'Trans Not Allow Fr This Prd',
				'created_at' => $now,
				'updated_at' => $now,
			),
			48 => array (
				'code' => '498',
				'description' => 'Cancelled by Bank',
				'remarks' => 'Cancelled by Bank',
				'created_at' => $now,
				'updated_at' => $now,
			),
			49 => array (
				'code' => '499',
				'description' => 'Cancelled by Customer',
				'remarks' => 'Cancelled by Customer',
				'created_at' => $now,
				'updated_at' => $now,
			),
			50 => array (
				'code' => '502',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'DECEASED (CIF)',
				'created_at' => $now,
				'updated_at' => $now,
			),
			51 => array (
				'code' => '503',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'RECEIVERSHIP (CIF)',
				'created_at' => $now,
				'updated_at' => $now,
			),
			52 => array (
				'code' => '504',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'BANKRUPT (CIF)',
				'created_at' => $now,
				'updated_at' => $now,
			),
			53 => array (
				'code' => '505',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'LIQUIDATION (CIF)',
				'created_at' => $now,
				'updated_at' => $now,
			),
			54 => array (
				'code' => '506',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'INSANE (CIF)',
				'created_at' => $now,
				'updated_at' => $now,
			),
			55 => array (
				'code' => '507',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'P/SHIP DISSOLVE(CIF)',
				'created_at' => $now,
				'updated_at' => $now,
			),
			56 => array (
				'code' => '508',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'COURT ORDER (CIF)',
				'created_at' => $now,
				'updated_at' => $now,
			),
			57 => array (
				'code' => '509',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'IN DISPUTE (CIF)',
				'created_at' => $now,
				'updated_at' => $now,
			),
			58 => array (
				'code' => '510',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'WHOLE BAL HOLD (CIF)',
				'created_at' => $now,
				'updated_at' => $now,
			),
			59 => array (
				'code' => '511',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'BAD (CIF)',
				'created_at' => $now,
				'updated_at' => $now,
			),
			60 => array (
				'code' => '512',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'DOUBTFUL (CIF)',
				'created_at' => $now,
				'updated_at' => $now,
			),
			61 => array (
				'code' => '514',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'SUB-STANDARD (CIF)',
				'created_at' => $now,
				'updated_at' => $now,
			),
			62 => array (
				'code' => '516',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'COMA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			63 => array (
				'code' => '522',
				'description' => 'Transaction Cannot be Completed',
				'remarks' => 'LOSS (CIF)',
				'created_at' => $now,
				'updated_at' => $now,
			),
			64 => array (
				'code' => '611',
				'description' => 'Exceed Giro Limit',
				'remarks' => 'Exceed Giro Limit',
				'created_at' => $now,
				'updated_at' => $now,
			),
			65 => array (
				'code' => '615',
				'description' => 'INV A/C NO',
				'remarks' => 'INV A/C NO',
				'created_at' => $now,
				'updated_at' => $now,
			),
			66 => array (
				'code' => '616',
				'description' => 'Invalid FI ID / Invalid Routing Number',
				'remarks' => 'Invalid FI ID / Invalid Routing Number',
				'created_at' => $now,
				'updated_at' => $now,
			),
			67 => array (
				'code' => '617',
				'description' => 'Invalid Company Ident.',
				'remarks' => 'Invalid Company Ident.',
				'created_at' => $now,
				'updated_at' => $now,
			),
			68 => array (
				'code' => '618',
				'description' => 'Amt > trxn limit for external a/c',
				'remarks' => 'Amt > trxn limit for external a/c',
				'created_at' => $now,
				'updated_at' => $now,
			),
			69 => array (
				'code' => '619',
				'description' => 'Invalid / Missing ID Number',
				'remarks' => 'Invalid / Missing ID Number',
				'created_at' => $now,
				'updated_at' => $now,
			),
			70 => array (
				'code' => '626',
				'description' => 'Credit date is passed',
				'remarks' => 'Credit date is passed',
				'created_at' => $now,
				'updated_at' => $now,
			),
			71 => array (
				'code' => '629',
				'description' => 'NOT FOUND IN HISTORY FILE',
				'remarks' => 'NOT FOUND IN HISTORY FILE',
				'created_at' => $now,
				'updated_at' => $now,
			),
			72 => array (
				'code' => '630',
				'description' => 'Insufficient fund due to OA',
				'remarks' => 'Insufficient fund due to OA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			73 => array (
				'code' => '631',
				'description' => 'GENERAL REJECT',
				'remarks' => 'GENERAL REJECT',
				'created_at' => $now,
				'updated_at' => $now,
			),
			74 => array (
				'code' => '632',
				'description' => 'INVALID DATA',
				'remarks' => 'INVALID DATA',
				'created_at' => $now,
				'updated_at' => $now,
			),
		));
	}
}
?>
