<?php

use Illuminate\Database\Seeder;

class StateTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		\DB::table('state')->truncate();
        $now = \Carbon\Carbon::now()->toDateTimeString();
		\DB::table('state')->insert(array (
			0 => array (
				'name' => 'Johor',
				'code' => 'MY01',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			1 => array (
				'name' => 'Kedah',
				'code' => 'MY02',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			2 => array (
				'name' => 'Kelantan',
				'code' => 'MY03',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			3 => array (
				'name' => 'Melaka',
				'code' => 'MY04',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			4 => array (
				'name' => 'Negeri Sembilan',
				'code' => 'MY05',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			5 => array (
				'name' => 'Pahang',
				'code' => 'MY06',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			6 => array (
				'name' => 'Perak',
				'code' => 'MY07',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			7 => array (
				'name' => 'Perlis',
				'code' => 'MY08',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			8 => array (
				'name' => 'Pulau Pinang',
				'code' => 'MY09',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			9 => array (
				'name' => 'Sarawak',
				'code' => 'MY11',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			10 => array (
				'name' => 'Selangor',
				'code' => 'MY12',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			11 => array (
				'name' => 'Terengganu',
				'code' => 'MY13',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			12 => array (
				'name' => 'Kuala Lumpur, Wilayah Persekutuan',
				'code' => 'MY14',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			13 => array (
				'name' => 'Labuan, Wilayah Persekutuan',
				'code' => 'MY15',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			14 => array (
				'name' => 'Sabah',
				'code' => 'MY16',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			15 => array (
				'name' => 'Putrajaya, Wilayah Persekutuan',
				'code' => 'MY17',
				'country_code' => 'MYS',
				'created_at' => $now,
				'updated_at' => $now,
			),
			16 => array (
				'name' => 'Andaman and Nicobar Islands',
				'code' => 'IN1',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			17 => array (
				'name' => 'Andhra Pradesh',
				'code' => 'IN2',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			18 => array (
				'name' => 'Arunachal Pradesh',
				'code' => 'IN3',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			19 => array (
				'name' => 'Assam',
				'code' => 'IN4',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			20 => array (
				'name' => 'Bihar',
				'code' => 'IN5',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			21 => array (
				'name' => 'Chandigarh',
				'code' => 'IN6',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			22 => array (
				'name' => 'Chhattisgarh',
				'code' => 'IN7',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			23 => array (
				'name' => 'Dadra and Nagar Haveli',
				'code' => 'IN8',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			24 => array (
				'name' => 'Daman and Diu',
				'code' => 'IN9',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			25 => array (
				'name' => 'National Capital Territory of Delhi',
				'code' => 'IN10',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			26 => array (
				'name' => 'Goa',
				'code' => 'IN11',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			27 => array (
				'name' => 'Gujarat',
				'code' => 'IN12',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			28 => array (
				'name' => 'Haryana',
				'code' => 'IN13',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			29 => array (
				'name' => 'Himachal Pradesh',
				'code' => 'IN14',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			30 => array (
				'name' => 'Jammu and Kashmir',
				'code' => 'IN15',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			31 => array (
				'name' => 'Jharkhand',
				'code' => 'IN16',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			32 => array (
				'name' => 'Karnataka',
				'code' => 'IN17',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			33 => array (
				'name' => 'Kerala',
				'code' => 'IN18',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			34 => array (
				'name' => 'Lakshadweep',
				'code' => 'IN19',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			35 => array (
				'name' => 'Madhya Pradesh',
				'code' => 'IN20',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			36 => array (
				'name' => 'Maharashtra',
				'code' => 'IN21',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			37 => array (
				'name' => 'Manipur',
				'code' => 'IN22',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			38 => array (
				'name' => 'Meghalaya',
				'code' => 'IN23',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			39 => array (
				'name' => 'Mizoram',
				'code' => 'IN24',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			40 => array (
				'name' => 'Nagaland',
				'code' => 'IN25',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			41 => array (
				'name' => 'Odisha',
				'code' => 'IN26',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			42 => array (
				'name' => 'Puducherry',
				'code' => 'IN27',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			43 => array (
				'name' => 'Punjab',
				'code' => 'IN28',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			44 => array (
				'name' => 'Rajasthan',
				'code' => 'IN29',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			45 => array (
				'name' => 'Sikkim',
				'code' => 'IN30',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			46 => array (
				'name' => 'Tamil Nadu',
				'code' => 'IN31',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			47 => array (
				'name' => 'Telangana',
				'code' => 'IN32',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			48 => array (
				'name' => 'Tripura',
				'code' => 'IN33',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			49 => array (
				'name' => 'Uttar Pradesh',
				'code' => 'IN34',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			50 => array (
				'name' => 'Uttarakhand',
				'code' => 'IN35',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			51 => array (
				'name' => 'West Bengal',
				'code' => 'IN36',
				'country_code' => 'IND',
				'created_at' => $now,
				'updated_at' => $now,
			),
			52 => array (
				'name' => 'Alabama',
				'code' => 'AL',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			53 => array (
				'name' => 'Alaska',
				'code' => 'AK',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			54 => array (
				'name' => 'Arizona',
				'code' => 'AZ',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			55 => array (
				'name' => 'Arkansas',
				'code' => 'AR',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			56 => array (
				'name' => 'Califonia',
				'code' => 'CA',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			57 => array (
				'name' => 'Colorado',
				'code' => 'CO',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			58 => array (
				'name' => 'Connecticut',
				'code' => 'CT',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			59 => array (
				'name' => 'Delaware',
				'code' => 'DE',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			60 => array (
				'name' => 'Florida',
				'code' => 'FL',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			61 => array (
				'name' => 'Georgia',
				'code' => 'GA',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			62 => array (
				'name' => 'Hawaii',
				'code' => 'HI',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			63 => array (
				'name' => 'Idaho',
				'code' => 'ID',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			64 => array (
				'name' => 'Illinois',
				'code' => 'IL',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			65 => array (
				'name' => 'Indiana',
				'code' => 'IN',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			66 => array (
				'name' => 'Iowa',
				'code' => 'IA',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			67 => array (
				'name' => 'Kansas',
				'code' => 'KS',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			68 => array (
				'name' => 'Kentucky',
				'code' => 'KY',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			69 => array (
				'name' => 'Louisiana',
				'code' => 'LA',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			70 => array (
				'name' => 'Maine',
				'code' => 'ME',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			71 => array (
				'name' => 'Maryland',
				'code' => 'MD',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			72 => array (
				'name' => 'Massachusetts',
				'code' => 'MA',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			73 => array (
				'name' => 'Michigan',
				'code' => 'MI',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			74 => array (
				'name' => 'Minnesota',
				'code' => 'MN',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			75 => array (
				'name' => 'Mississippi',
				'code' => 'MS',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			76 => array (
				'name' => 'Missouri',
				'code' => 'MO',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			77 => array (
				'name' => 'Montana',
				'code' => 'MT',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			78 => array (
				'name' => 'Nebraska',
				'code' => 'NE',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			79 => array (
				'name' => 'Nevada',
				'code' => 'NV',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			80 => array (
				'name' => 'New Hampshire',
				'code' => 'NH',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			81 => array (
				'name' => 'New Jersey',
				'code' => 'NJ',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			82 => array (
				'name' => 'New Mexico',
				'code' => 'NM',
				'country_code' => 'USA',
				'created_at' => $now,
			   'updated_at' => $now,
			),
			83 => array (
				'name' => 'New York',
				'code' => 'NY',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			84 => array (
				'name' => 'North Carolina',
				'code' => 'NC',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			85 => array (
				'name' => 'North Dakota',
				'code' => 'ND',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			86 => array (
				'name' => 'Ohio',
				'code' => 'OH',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			87 => array (
				'name' => 'Oklahoma',
				'code' => 'OK',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			88 => array (
				'name' => 'Oregon',
				'code' => 'OR',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			89 => array (
				'name' => 'Pennsylvania',
				'code' => 'PA',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			90 => array (
			   'name' => 'Rhode Island',
				'code' => 'RI',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			91 => array (
				'name' => 'South Carolina',
				'code' => 'SC',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			92 => array (
				'name' => 'South Dakota',
				'code' => 'SD',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			93 => array (
				'name' => 'Tennessee',
				'code' => 'TN',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			94 => array (
				'name' => 'Texas',
				'code' => 'TX',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			95 => array (
				'name' => 'Utah',
				'code' => 'UT',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			96 => array (
				'name' => 'Vermont',
				'code' => 'VT',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			97 => array (
				'name' => 'Virginia',
				'code' => 'VA',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			98 => array (
				'name' => 'Washington',
				'code' => 'WA',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			99 => array (
				'name' => 'West Virginia',
				'code' => 'WV',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			100 => array (
				'name' => 'Wisconsin',
				'code' => 'WI',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			101 => array (
				'name' => 'Wyoming',
				'code' => 'VY',
				'country_code' => 'USA',
				'created_at' => $now,
				'updated_at' => $now,
			),
			102 => array (
				'name' => 'Anhui',
				'code' => 'CH1',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			103 => array (
				'name' => 'Fujian',
				'code' => 'CH2',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			104 => array (
				'name' => 'Gansu',
				'code' => 'CH3',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			105 => array (
				'name' => 'Guangdong',
				'code' => 'CH4',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			106 => array (
				'name' => 'Guizhou',
				'code' => 'CH5',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			107 => array (
				'name' => 'Hainan',
				'code' => 'CH6',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			108 => array (
				'name' => 'Hebei',
				'code' => 'CH7',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			109 => array (
				'name' => 'Heilongjiang ',
				'code' => 'CH8',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			110 => array (
				'name' => 'Henan',
				'code' => 'CH9',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),

			111 => array (
				'name' => 'Hubei',
				'code' => 'CH10',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),

			112  => array (
				'name' => 'Hunan',
				'code' => 'CH11',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			113 => array (
				'name' => 'Jiangsu',
				'code' => 'CH12',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),

			114 => array (
				'name' => 'Jiangxi',
				'code' => 'CH13',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			115 => array (
				'name' => 'Jilin',
				'code' => 'CH14',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			116 => array (
				'name' => 'Liaoning',
				'code' => 'CH15',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			117 => array (
				'name' => 'Qinghai',
				'code' => 'CH16',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			118 => array (
				'name' => 'Shaanxi',
				'code' => 'CH17',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			119 => array (
				'name' => 'Shandong',
				'code' => 'CH18',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			120 => array (
				'name' => 'Shanxi',
				'code' => 'CH19',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			121 => array (
				'name' => 'Sichuan',
				'code' => 'CH20',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			122 => array (
				'name' => 'Yunnan',
				'code' => 'CH21',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			123 => array (
				'name' => 'Zhejiang',
				'code' => 'CH22',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			124 => array (
				'name' => 'Xinjiang',
				'code' => 'CH23',
				'country_code' => 'CHN',
				'created_at' => $now,
				'updated_at' => $now,
		  	),
			125 => array (
				'name' => 'Aguascalientes',
				'code' => 'MX01',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			126 => array (
				'name' => 'Baja California',
				'code' => 'MX02',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			127 => array (
				'name' => 'Baja California Sur',
				'code' => 'MX03',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			128 => array (
				'name' => 'Campeche',
				'code' => 'MX04',
				'country_code' => 'MEX',
		'created_at' => $now,
				'updated_at' => $now,
			),
			129 => array (
				'name' => 'Chiapas',
				'code' => 'MX05',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			130 => array (
				'name' => 'Chihuahua State',
				'code' => 'MX06',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			131 => array (
				'name' => 'Coahuila',
				'code' => 'MX07',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			132 => array (
				'name' => 'Colima',
				'code' => 'MX08',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			133 => array (
				'name' => 'Distrito Federal',
				'code' => 'MX09',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			134 => array (
				'name' => 'Durango',
				'code' => 'MX10',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			135 => array (
				'name' => 'Guanajuato',
				'code' => 'MX11',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			136 => array (
				'name' => 'Guerrero',
				'code' => 'MX12',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			137 => array (
				'name' => 'Hidalgo',
				'code' => 'MX13',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			138 => array (
				'name' => 'Jalisco',
				'code' => 'MX14',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			139 => array (
				'name' => 'Mexico State',
				'code' => 'MX15',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			140 => array (
				'name' => 'Michoacan',
				'code' => 'MX16',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			141 => array (
				'name' => 'Morelos',
				'code' => 'MX17',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			142 => array (
				'name' => 'Nayarit',
				'code' => 'MX18',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			143 => array (
				'name' => 'Nuevo Leon',
				'code' => 'MX19',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			144 => array (
				'name' => 'Oaxaca',
				'code' => 'MX20',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			145 => array (
				'name' => 'Puebla',
				'code' => 'MX21',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			146 => array (
				'name' => 'Queretaro',
				'code' => 'MX22',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			147 => array (
				'name' => 'Quintana Roo',
				'code' => 'MX23',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			148 => array (
				'name' => 'San Luis Potosi',
				'code' => 'MX24',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			149 => array (
				'name' => 'Sinaloa',
				'code' => 'MX25',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			150 => array (
				'name' => 'Sonora',
				'code' => 'MX26',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			151 => array (
				'name' => 'Tabasco',
				'code' => 'MX27',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			152 => array (
				'name' => 'Tamaulipas',
				'code' => 'MX28',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			153 => array (
				'name' => 'Tlaxcala',
				'code' => 'MX29',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			154 => array (
				'name' => 'Veracruz',
				'code' => 'MX30',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			155 => array (
				'name' => 'Yucatan',
				'code' => 'MX31',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			156 => array (
				'name' => 'Zacatecas',
				'code' => 'MX32',
				'country_code' => 'MEX',
				'created_at' => $now,
				'updated_at' => $now,
			),
			157 => array (
				'name' => 'Acre',
				'code' => 'BR01',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			158 => array (
				'name' => ' Alagoas',
				'code' => 'BR02',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			159 => array (
				'name' => 'Amapa',
				'code' => 'BR03',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			160 => array (
				'name' => 'Amazonas',
				'code' => 'BR04',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			161 => array (
				'name' => 'Bahia',
				'code' => 'BR05',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			162 => array (
				'name' => 'Ceara',
				'code' => 'BR06',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			163 => array (
				'name' => 'Distrito Federal',
				'code' => 'BR07',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			164 => array (
				'name' => 'Espirito Santo',
				'code' => 'BR08',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			165 => array (
				'name' => 'Mato Grosso do Sul',
				'code' => 'BR11',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			166 => array (
				'name' => 'Maranhao',
				'code' => 'BR13',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			167 => array (
				'name' => 'Mato Grosso',
				'code' => 'BR14',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			168 => array (
				'name' => 'Minas Gerais',
				'code' => 'BR15',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			169 => array (
				'name' => 'Para',
				'code' => 'BR16',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			170 => array (
				'name' => 'Paraiba',
				'code' => 'BR17',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			171 => array (
				'name' => 'Parana',
				'code' => 'BR18',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			172 => array (
				'name' => 'Piaui',
				'code' => 'BR20',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			173 => array (
				'name' => 'Rio de Janeiro',
				'code' => 'BR21',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			174 => array (
				'name' => 'Rio Grande do Norte',
				'code' => 'BR22',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			175 => array (
				'name' => 'Rio Grande do Sul',
				'code' => 'BR23',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			176 => array (
				'name' => 'Rondonia',
				'code' => 'BR24',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			177 => array (
				'name' => 'Roraima',
				'code' => 'BR25',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			178 => array (
				'name' => 'Santa Catarina',
				'code' => 'BR26',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			179 => array (
				'name' => 'Sao Paulo',
				'code' => 'BR27',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			180 => array (
				'name' => 'Sergipe',
				'code' => 'BR28',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			181  => array (
				'name' => 'Golas',
				'code' => 'BR29',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			182  => array (
				'name' => 'Pernambuco',
				'code' => 'BR30',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			183  => array (
				'name' => 'Tocantins',
				'code' => 'BR31',
				'country_code' => 'BRA',
				'created_at' => $now,
				'update_at' => $now,
			),
			184 => array (
				'name' => 'Aichi',
				'code' => 'JP23',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			185 => array (
				'name' => 'Akita',
				'code' => 'JP05',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			186 => array (
				'name' => 'Aomori',
				'code' => 'JP02',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			187 => array (
				'name' => 'Ehime',
				'code' => 'JP38',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			188 => array (
				'name' => 'Gihu',
				'code' => 'JP21',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			189 => array (
				'name' => 'Gunma',
				'code' => 'JP10',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			190 => array (
				'name' => 'Hirosima',
				'code' => 'JP34',
				'countryy_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			191 => array (
				'name' => 'Hokkaido',
				'code' => 'JP01',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			192 => array (
				'name' => 'Hukui',
				'code' => 'JP18',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			193 => array (
				'name' => 'Hukuoka',
				'code' => 'JP40',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			194 => array (
				'name' => 'Hukusima',
				'code' => 'JP07',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			195 => array (
				'name' => 'Hyogo',
				'code' => 'JP28',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			196 => array (
				'name' => 'Ibaraki',
				'code' => 'JP08',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			197 => array (
				'name' => 'Isikawa',
				'code' => 'JP17',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			198 => array (
				'name' => 'Iwate',
				'code' => 'JP03',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			199 => array (
				'name' => 'Kagawa',
				'code' => 'JP37',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			200 => array (
				'name' => 'Kagosima',
				'code' => 'JP46',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			201 => array (
				'name' => 'Kanagawa',
				'code' => 'JP14',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			202 => array (
				'name' => 'Koti',
				'code' => 'JP39',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			203 => array (
				'name' => 'Kumamoto',
				'code' => 'JP43',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			204 => array (
				'name' => 'Kyoto',
				'code' => 'JP26',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			205 => array (
				'name' => 'Mie',
				'code' => 'JP24',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			206 => array (
				'name' => 'Miyagi',
				'code' => 'JP04',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			207 => array (
				'name' => 'Miyazaki',
				'code' => 'JP45',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			208 => array (
				'name' => 'Nagano',
				'code' => 'JP20',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			209 => array (
				'name' => 'Nagasaki',
				'code' => 'JP42',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			210 => array (
				'name' => 'Nara',
				'code' => 'JP29',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			211 => array (
				'name' => 'Niigata',
				'code' => 'JP15',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			212 => array (
				'name' => 'Oita',
				'code' => 'JP44',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			213 => array (
				'name' => 'Okayama',
				'code' => 'JP33',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			214 => array (
				'name' => 'Okinawa',
				'code' => 'JP47',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			215 => array (
				'name' => 'Osaka',
				'code' => 'JP27',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			216 => array (
				'name' => 'Saga',
				'code' => 'JP41',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			217 => array (
				'name' => 'Saitama',
				'code' => 'JP11',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			218 => array (
				'name' => 'Siga',
				'code' => 'JP25',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			219 => array (
				'name' => 'Simane',
				'code' => 'JP32',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			220 => array (
				'name' => 'Sizuoka',
				'code'=> 'JP22',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			221 => array (
				'name' => 'Tiba',
				'code' => 'JP12',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			222 => array (
				'name' => 'Tokusima',
				'code' => 'JP36',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			223 => array (
				'name' => 'Tokyo',
				'code' => 'JP13',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			224 => array (
				'name' => 'Totigi',
				'code' => 'JP09',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			225 => array (
				'name' => 'Tottori',
				'code' => 'JP31',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			226 => array (
				'name' => 'Toyama',
				'code' => 'JP16',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			227 => array (
				'name' => 'Wakayama',
				'code' => 'JP30',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			228 => array (
				'name' => 'Yamagata',
				'code' => 'JP06',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			229 => array (
				'name' => 'Yamaguti',
				'code' => 'JP35',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			),
			230 => array (
				'name' => 'Yamanasi',
				'code' => 'JP19',
				'country_code' => 'JPN',
				'created_at' => '$now',
				'updated_at' => '$now',
			)

		));
		
		$states = DB::table('state')->where('country_code','MYS')->get();
		$id = 1;
		foreach($states as $state){
			DB::table('state')->where('id',$state->id)->update(['statecountry_id'=>$id]);
			$id++;
		}
		
    }
	
	
}
