<li><a href="{{route('MasterMerchant')}}">Merchant</a></li>
<li><a href="{{route('Station')}}">Station</a></li>
<li><a href="{{route('MasterBuyer')}}">Buyer</a></li>
<li><a href="{{route('Product')}}">Product</a></li>
{{--<li><a href="{{route('ProductTerm')}}">Term Product </a></li>--}}
<li><a href="{{route('Order')}}">Order</a></li>
<li><a href="{{route('OrderTerm')}}">Term Order </a></li>
<li><a href="{{route('MasterOshop')}}">O-Shop</a></li>
<li><a href="{{route('cre')}}">CRE</a></li>
<li><a href="{{url('/admin/master/voucher')}}">Voucher</a></li>
<li><a href="{{url('admin/master/discount')}}">Discount</a></li>
<li><a href="{{url('admin/master/hyper')}}">Hyper</a></li>
<li><a href="{{route('routeOpenWish')}}">OpenWish</a></li>
<li><a href="{{route('masterSMM')}}">SMM</a></li>
<li><a href="{{route('MasterMerchantConsultant')}}">Merchant Consultant</a></li>
<li><a href="{{route('MasterMerchantProfessional')}}">Merchant Professional</a></li>
<li><a href="{{route('MasterMerchantCampaign')}}">Merchant Campaign</a></li>
{{--<li><a href="{{route('station_recruiter')}}">Station Recruiter</a></li> --}}
<li><a href="{{route('routeEmployee')}}">Employee</a></li>
<li><a href="#">Professional Integrator</a></li>
<li><a href="{{route('openchannel')}}">OpenChannel</a></li>
{{-- <li><a href="{{route('Property')}}">Station Property</a></li> --}}
<li><a href="{{url('admin/master/autolink')}}">AutoLink</a></li>
{{--<li><a href="{{route('shipping:world')}}">Delivery</a></li>--}}
<li><a href="{{ route('openCredit') }}">OpenCredit</a></li>
{{--<li><a href="{{url('admin/master/delivery')}}">Delivery</a></li>--}}
<li><a href="{{url('admin/master/token')}}">Token</a></li>
<li><a href="{{url('admin/master/investment')}}">Investment</a></li>
<li><a href="{{url('admin/master/wishlist')}}">Wishlist</a></li>
<li><a href="{{url('admin/master/humancap')}}">HumanCap</a></li>
{{--<li><a href="#">Auction</a></li>--}}
{{--<li><a href="#">Loyalty</a></li>--}}
