<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateFpxACTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('fpx_AC', function (Blueprint $table) {
            $table->increments('id');
			/* 1. Indicate message type: AC */
            $table->string('fpx_msgType',2)->default('AC');

			/* 2. Indicate business model: 01-B2C, 02-B2B1, 03-B2B2 */
			$table->tinyInteger('fpx_msgToken')->unsigned();

			/* 3. Unique ID generated by FPX fo reach payment request received
			 * from Merchant: YYMMDDHH24MISS#### */
			$table->string('fpx_fpxTxnId',16);

			/* 4. Exchange ID -provided by FPX */
			$table->string('fpx_sellerExId',10);

			/* 5. Unique ID generated by Exchange for each transaction
			 * originating from an Exchange */
			$table->string('fpx_sellerExOrderNo',40);

			/* 6. Date and time FPX processed transaction
			 * YYYYMMDDHH24MISS (in MYT) */
			$table->datetime('fpx_fpxTxnTime');
 
			/* 7. Date and time transaction originated from merchant
			 * YYYYMMDDHH24MISS (in MYT) */
			$table->datetime('fpx_sellerTxnTime');

			/* 8. Order number generated by Merchant */
			$table->string('fpx_sellerOrderNo',40);

			/* 9. Seller ID - provided by FPX */
			$table->string('fpx_sellerId',10);

			/* 10. Transaction Currency: default = "MYR" */
			$table->string('fpx_txnCurrency',3)->default('MYR');

			/* 11. Total Amount */
			$table->float('fpx_txnAmount',16,2);

			/* 12. Checksum value: Hold message signature */
			$table->string('fpx_checkSum');

			/* 13. Buyer name */
			$table->string('fpx_buyerName',40);

 			/* 14. Provided by FPX: ties to Bank that Buyer has an account */
			$table->string('fpx_buyerBankId',10);

			/* 15. Bank's branch code that Buyer opened his account */
			$table->string('fpx_buyerBankBranch',10);

			/* 16. Buyer identification number */
			$table->string('fpx_buyerId',20);

			/* 17. Buyer representative (Maker) who initiate the transaction */
			$table->string('fpx_makerName',40);

			/* 18. Buyer IBAN */
			$table->string('fpx_buyerIban',35);

			/* 19. Debit response code authorized by Buyer Bank */
			$table->string('fpx_debitAuthCode',2);

			/* 20. Mandatory if Debit Authorization Code is '00' */
			$table->string('fpx_debitAuthNo',10);

			/* 21. Credit response code authorized by Acquiring Bank */
			$table->string('fpx_creditAuthCode',2);

			/* 22. Mandatory if Credit Authorization Code is '00' */
			$table->string('fpx_creditAuthNo',10);
 
            $table->softDeletes();
            $table->timestamps();
            $table->engine = "MYISAM";
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('fpx_AC');
    }
}
