<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateFpxARTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('fpx_AR', function (Blueprint $table) {
            $table->increments('id');
			/* 1. Indicate message type: AR/AE */
            $table->string('fpx_msgType',2);

			/* 2. Indicate business model: 01-B2C, 02-B2B1, 03-B2B2 */
			$table->tinyInteger('fpx_msgToken')->unsigned();

			/* 3. Exchange ID -provided by FPX */
			$table->string('fpx_sellerExId',10);

			/* 4. Unique ID generated by Exchange for each transaction
			 * originating from an Exchange */
			$table->string('fpx_sellerExOrderNo',40);

			/* 5. Date and time transaction originated from merchant */
			$table->datetime('fpx_sellerTxnTime');

			/* 6. Order number generated by Merchant */
			$table->string('fpx_sellerOrderNo',40);

			/* 7. Seller ID - provided by FPX */
			$table->string('fpx_sellerId',10);

			/* 8. Seller account no. registered in FPX: 01, 02, 03, 04 */
			$table->tinyInteger('fpx_sellerBankCode')->default(1);

			/* 9. Transaction Currency: default = "MYR" */
			$table->string('fpx_txnCurrency',3)->default('MYR');

			/* 10. Total Amount */
			$table->float('fpx_txnAmount',16,2);

			/* 11. Buyer email address */
			$table->string('fpx_buyerEmail',50);

			/* 12. Checksum value: Hold message signature */
			$table->string('fpx_checkSum');

			/* 13. Buyer name */
			$table->string('fpx_buyerName',40);

			/* 14. Provided by FPX: ties to Bank that Buyer has an account */
			$table->string('fpx_buyerBankId',10);

			/* 15. Bank's branch code that Buyer opened his account */
			$table->string('fpx_buyerBankBranch',10);

			/* 16. Buyer account number */
			$table->string('fpx_buyerAccNo',20);

			/* 17. Buyer Identification Number */
			$table->string('fpx_buyerId',20);

			/* 18. Buyer representative (Maker) who initiate the transaction */
			$table->string('fpx_makerName',40);

			/* 19. Buyer IBAN */
			$table->string('fpx_buyerIban',35);

			/* 20. Product Description */
			$table->string('fpx_productDesc',30);

			/* 21: Version number: default = 6.0 */
			$table->tinyInteger('fpx_version')->default(6);


            $table->softDeletes();
            $table->timestamps();
            $table->engine = 'MYISAM';
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('fpx_AR');
    }
}
