<?php

use Illuminate\Database\Seeder;

class MerchantProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('merchantproduct')->truncate();
        $now = \Carbon\Carbon::now()->toDateTimeString();
        \DB::table('merchantproduct')->insert(array (
            0 => array(
                'merchant_id' => 1,
                'product_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            1 => array(
                'merchant_id' => 1,
                'product_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            2 => array(
                'merchant_id' => 1,
                'product_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            3 => array(
                'merchant_id' => 1,
                'product_id' => 4,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            4 => array(
                'merchant_id' => 1,
                'product_id' => 5,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            5 => array(
                'merchant_id' => 1,
                'product_id' => 6,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            6 => array(
                'merchant_id' => 1,
                'product_id' => 7,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            7 => array(
                'merchant_id' => 1,
                'product_id' => 8,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            8 => array(
                'merchant_id' => 1,
                'product_id' => 9,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            9 => array(
                'merchant_id' => 1,
                'product_id' => 10,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            10 => array(
                'merchant_id' => 1,
                'product_id' => 11,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            11 => array(
                'merchant_id' => 1,
                'product_id' => 12,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            12 => array(
                'merchant_id' => 1,
                'product_id' => 13,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            13 => array(
                'merchant_id' => 1,
                'product_id' => 14,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            14 => array(
                'merchant_id' => 1,
                'product_id' => 15,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            15 => array(
                'merchant_id' => 1,
                'product_id' => 16,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            16 => array(
                'merchant_id' => 1,
                'product_id' => 17,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            17 => array(
                'merchant_id' => 6,
                'product_id' => 18,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            18 => array(
                'merchant_id' => 6,
                'product_id' => 19,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            19 => array(
                'merchant_id' => 6,
                'product_id' => 20,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            20 => array(
                'merchant_id' => 6,
                'product_id' => 21,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            21 => array(
                'merchant_id' => 6,
                'product_id' => 22,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            22 => array(
                'merchant_id' => 6,
                'product_id' => 23,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            23 => array(
                'merchant_id' => 11,
                'product_id' => 24,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            24 => array(
                'merchant_id' => 11,
                'product_id' => 25,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            25 => array(
                'merchant_id' => 11,
                'product_id' => 26,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            26 => array(
                'merchant_id' => 11,
                'product_id' => 27,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            27 => array(
                'merchant_id' => 11,
                'product_id' => 28,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            28 => array(
                'merchant_id' => 11,
                'product_id' => 29,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            29 => array(
                'merchant_id' => 16,
                'product_id' => 30,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            30 => array(
                'merchant_id' => 16,
                'product_id' => 31,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            31 => array(
                'merchant_id' => 16,
                'product_id' => 32,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            32 => array(
                'merchant_id' => 16,
                'product_id' => 33,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            33 => array(
                'merchant_id' => 16,
                'product_id' => 34,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            34 => array(
                'merchant_id' => 16,
                'product_id' => 35,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            35 => array(
                'merchant_id' => 21,
                'product_id' => 36,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            36 => array(
                'merchant_id' => 21,
                'product_id' => 37,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            37 => array(
                'merchant_id' => 21,
                'product_id' => 38,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            38 => array(
                'merchant_id' => 21,
                'product_id' => 39,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            39 => array(
                'merchant_id' => 21,
                'product_id' => 40,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            40 => array(
                'merchant_id' => 21,
                'product_id' => 41,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            41 => array(
                'merchant_id' => 21,
                'product_id' => 42,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            42 => array(
                'merchant_id' => 26,
                'product_id' => 43,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            43 => array(
                'merchant_id' => 26,
                'product_id' => 44,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            44 => array(
                'merchant_id' => 26,
                'product_id' => 45,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            45 => array(
                'merchant_id' => 26,
                'product_id' => 46,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            46 => array(
                'merchant_id' => 26,
                'product_id' => 47,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            47 => array(
                'merchant_id' => 26,
                'product_id' => 48,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            48 => array(
                'merchant_id' => 31,
                'product_id' => 49,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            49 => array(
                'merchant_id' => 31,
                'product_id' => 50,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            50 => array(
                'merchant_id' => 31,
                'product_id' => 51,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            51 => array(
                'merchant_id' => 31,
                'product_id' => 52,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            52 => array(
                'merchant_id' => 31,
                'product_id' => 53,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            53 => array(
                'merchant_id' => 31,
                'product_id' => 54,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            54 => array(
                'merchant_id' => 36,
                'product_id' => 55,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            55 => array(
                'merchant_id' => 36,
                'product_id' => 56,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            56 => array(
                'merchant_id' => 36,
                'product_id' => 57,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            57 => array(
                'merchant_id' => 36,
                'product_id' => 58,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            58 => array(
                'merchant_id' => 36,
                'product_id' => 59,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            59 => array(
                'merchant_id' => 36,
                'product_id' => 60,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            60 => array(
                'merchant_id' => 41,
                'product_id' => 61,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            61 => array(
                'merchant_id' => 41,
                'product_id' => 62,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            62 => array(
                'merchant_id' => 41,
                'product_id' => 63,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            63 => array(
                'merchant_id' => 41,
                'product_id' => 64,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            64 => array(
                'merchant_id' => 41,
                'product_id' => 65,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            65 => array(
                'merchant_id' => 41,
                'product_id' => 66,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            66 => array(
                'merchant_id' => 46,
                'product_id' => 67,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            67 => array(
                'merchant_id' => 46,
                'product_id' => 68,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            68 => array(
                'merchant_id' => 46,
                'product_id' => 69,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            69 => array(
                'merchant_id' => 46,
                'product_id' => 70,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            70 => array(
                'merchant_id' => 46,
                'product_id' => 71,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            71 => array(
                'merchant_id' => 46,
                'product_id' => 72,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            72 => array(
                'merchant_id' => 43,
                'product_id' => 73,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            73 => array(
                'merchant_id' => 43,
                'product_id' => 74,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            74 => array(
                'merchant_id' => 43,
                'product_id' => 75,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            75 => array(
                'merchant_id' => 43,
                'product_id' => 76,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            76 => array(
                'merchant_id' => 43,
                'product_id' => 77,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            77 => array(
                'merchant_id' => 43,
                'product_id' => 78,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            78 => array(
                'merchant_id' => 49,
                'product_id' => 79,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            79 => array(
                'merchant_id' => 49,
                'product_id' => 80,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            80 => array(
                'merchant_id' => 49,
                'product_id' => 81,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            81 => array(
                'merchant_id' => 49,
                'product_id' => 82,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            82 => array(
                'merchant_id' => 49,
                'product_id' => 83,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            83 => array(
                'merchant_id' => 49,
                'product_id' => 84,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            84 => array(
                'merchant_id' => 50,
                'product_id' => 85,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            85 => array(
                'merchant_id' => 51,
                'product_id' => 86,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            86 => array(
                'merchant_id' => 51,
                'product_id' => 87,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            87 => array(
                'merchant_id' => 51,
                'product_id' => 88,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            88 => array(
                'merchant_id' => 51,
                'product_id' => 89,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            89 => array(
                'merchant_id' => 51,
                'product_id' => 90,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            90 => array(
                'merchant_id' => 51,
                'product_id' => 91,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            91 => array(
                'merchant_id' => 51,
                'product_id' => 92,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            92 => array(
                'merchant_id' => 51,
                'product_id' => 93,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            93 => array(
                'merchant_id' => 51,
                'product_id' => 94,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            94 => array(
                'merchant_id' => 51,
                'product_id' => 95,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            95 => array(
                'merchant_id' => 51,
                'product_id' => 96,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            96 => array(
                'merchant_id' => 52,
                'product_id' => 97,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            97 => array(
                'merchant_id' => 52,
                'product_id' => 98,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            98 => array(
                'merchant_id' => 52,
                'product_id' => 99,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            99 => array(
                'merchant_id' => 52,
                'product_id' => 100,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            100 => array(
                'merchant_id' => 52,
                'product_id' => 101,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            101 => array(
                'merchant_id' => 52,
                'product_id' => 102,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            102 => array(
                'merchant_id' => 52,
                'product_id' => 103,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            103 => array(
                'merchant_id' => 52,
                'product_id' => 104,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            104 => array(
                'merchant_id' => 52,
                'product_id' => 105,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            105 => array(
                'merchant_id' => 52,
                'product_id' => 106,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            106 => array(
                'merchant_id' => 52,
                'product_id' => 107,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            107 => array(
                'merchant_id' => 52,
                'product_id' => 108,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            108 => array(
                'merchant_id' => 52,
                'product_id' => 109,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            109 => array(
                'merchant_id' => 52,
                'product_id' => 110,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            110 => array(
                'merchant_id' => 52,
                'product_id' => 111,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            111 => array(
                'merchant_id' => 52,
                'product_id' => 112,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            112 => array(
                'merchant_id' => 52,
                'product_id' => 113,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            113 => array(
                'merchant_id' => 52,
                'product_id' => 114,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            114 => array(
                'merchant_id' => 52,
                'product_id' => 115,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            115 => array(
                'merchant_id' => 52,
                'product_id' => 116,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            116 => array(
                'merchant_id' => 52,
                'product_id' => 117,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
            117 => array(
                'merchant_id' => 52,
                'product_id' => 118,
                'created_at'  => $now,
                'updated_at'  => $now,
            ),
           
        ));
    }
}
